### PR TITLE
Fix definition of CUDA_PATH in CUDA 12

### PR DESCRIPTION
**Pull request by traversaro**
Based on https://github.com/conda-forge/onnxruntime-feedstock/pull/115#issuecomment-2114935030 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Review by flferretti — APPROVED** [review]
Thanks a lot @traversaro, LGTM

**Comment by traversaro** [comment]
(No need to bump the build number).

**Comment by jakirkham** [comment]
Thanks Silvio! 🙏

Noticed the same thing in PR ( https://github.com/conda-forge/warp-lang-feedstock/pull/13 ) (much later than you did) and was pleasantly surprised that you already fixed it! 😄

**Pull request merged**
