### PR TITLE
Update version to v1.4.0

### LINKED ISSUE #31: @conda-forge-admin, please update version
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by flferretti**
Close #32 
Close #31

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by flferretti** [comment]
The build with Linux, Cuda12.0 and Python 3.10 is failing, but it seems to be unrelated to the PR. Restarting CI

**Comment by flferretti** [comment]
@conda-forge-admin, please restart ci

**Comment by flferretti** [comment]
@traversaro `warp-lang-feedstock (win win_64_cuda_compilernvcccuda_compiler_version11.8python3.10.____cpython)` has been cancelled, but I don't understand why. Do you perhaps have any idea?

**Comment by traversaro** [comment]
> @traversaro `warp-lang-feedstock (win win_64_cuda_compilernvcccuda_compiler_version11.8python3.10.____cpython)` has been cancelled, but I don't understand why. Do you perhaps have any idea?

Is this still the case? It seem that now the build is green.

**Comment by flferretti** [comment]
> Is this still the case? It seem that now the build is green.

Apparently not. I don't know what happened

**Review by traversaro — APPROVED** [review]

**Pull request merged**
